# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install gulp -g
          - npm install typings -g
          - typings install
          - gulp build.prod
          #- npm test

    - step:
        caches:
          - node
        image: python:3.5.1
        script: # Modify the commands below to build your repository.
          - apt-get update # required to install zip
          - apt-get install -y zip # required for packaging up the application
          - pip install boto3==1.3.0 # required for codedeploy_deploy.py
          - zip -r /tmp/artifact.zip * # package up the application for deployment
          - python codedeploy_deploy.py # run the deployment script
