# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.8.1

pipelines:
  custom: # Pipelines that are triggered automatically
    master:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository..
          - node -v
          - npm -v
          - npm install
          - npm rebuild
          - npm install gulp -g
          - npm install typings -g
          - typings install
          - gulp build.prod
        artifacts:
          - dist/**
    - step:
           name : Create a MyBuildCost Production Artifact
           script:
              - echo $APPLICATION_NAME
              - apt-get update
              - apt-get install -y zip
              - zip -r MyBuilCost_Production_Artifacts.zip dist/** package.json
              - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/scripts/startApp.sh" -u "AnilGadge:WYpAaN7ce8uwFzG3nzur"
              - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/MyBuilCost_Production_Artifacts.zip" -u "AnilGadge:WYpAaN7ce8uwFzG3nzur"
