# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install gulp -g
          - npm install typings -g
          - typings install
          - gulp build.prod
          #- apt-get update # required to install zip
          #- apt-get install -y zip # required for packaging up the application
          #- wget http://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz#md5=62a9f08dd5dc69d76734568a6c040508
          #- tar -xvf pip*.gz
          #- cd pip*
          #- python setup.py install
          #- pip install boto3==1.3.0 # required for codedeploy_deploy.py
          #- zip -r /tmp/artifact.zip * # package up the application for deployment
          #- python codedeploy_deploy.py # run the deployment script# npm test
