# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.8.1

pipelines:
  branches: # Pipelines that are triggered manually
    build-info-staging:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo $APPLICATION_NAME
          - echo $APPLICATION_NAME
          - node -v
          - npm -v
          - npm install
          - npm rebuild
          - npm install gulp -g
          - npm install typings -g
          - typings install
          - gulp build.prod
           # AUTO VERSIONING
                    - git config remote.origin.url https://NiteshGotmare@bitbucket.org/tplabs/costcontrol.git
                    - gulp autoversion
                    - git init
                    - git config user.name "Nitesh"
                    - git config user.email "nitesh.gotmare@techprimelab.com"
                    - git add package.json
                    - git commit -m "[skip CI]"
                    - git push
                    - declare -x VERSION=$(jq -r '.version' package.json)
                    - echo $VERSION
                    - git tag $VERSION
                    - git remote -v
                    - git push origin --tags
        artifacts:
          - dist/**
    - step:
            script:
              - apt-get update # required to install zip
              - apt-get install -y zip # required for packaging up the application
              - apt-get install python-pip -y
              - pip install boto3==1.3.0 # required for codedeploy_deploy.py
              - zip -r /tmp/artifact.zip dist/** appspec.yml package.json scripts # package up the application for deployment
              - python codedeploy_deploy.py # run the deployment script
