# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.8.1

pipelines:
  custom: # Pipelines that are triggered automatically
    build-info-staging:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository..
          #- echo $APPLICATION_NAME
          #- echo $APPLICATION_NAME
          - node -v
          - npm -v
          - npm install
          - npm rebuild
          - npm install gulp -g
          - npm install typings -g
          - typings install
          - gulp build.prod
        artifacts:
          - dist/**
    - step:
            script:
              - apt-get update # required to install zip
              - apt-get install -y zip # required for packaging up the application
              #- apt-get install python-pip -y
              #- pip install boto3==1.3.0 # required for codedeploy_deploy.py
              - zip -r new_artifact.zip dist/** # package up the application for deployment
              - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/new_artifact.zip" -u "AnilGadge:WYpAaN7ce8uwFzG3nzur"
              - ls
              #- python codedeploy_deploy.py # run the deployment script
